# Generated by Django 2.0.9 on 2018-10-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_auto_20181010_1250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="properties",
            name="furnished",
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="properties",
            name="rent",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="properties",
            name="rooms",
            field=models.CharField(max_length=1),
        ),
    ]
